### ISSUE TITLE
backlight's brightness not working under i3

### ISSUE THREAD

**Issue by anchnk** [anchnk/dotfiles#1]
# Problem

Brightness control keys work under **Unity** but not under **i3-gaps**.
For some reason the `xbacklight` program doesn't resolve the issue even using`sudo`. 
Writing as a super user to the file `/sys/class/backlight/intel_backlight/brightness` works.

Versions:
- i3 : 4.13-116-gfdf5d3a
- ubuntu : 16.04.1

**Comment by anchnk** [comment]
This [thread](https://www.reddit.com/r/i3wm/comments/4m5umz/help_with_screen_brightness/) suggest to use the `brightlight` binary as a workaround.

**Comment by anchnk** [comment]
## Solution

Using  [`brightlight`](https://github.com/multiplexd/brightlight) worked under Ubuntu 16.04

Clone, install dependencies, compile and install brightlight binary with SUID bit

    $ git clone https://github.com/multiplexd/brightlight.git
    $ sudo apt install libbsd-dev
    $ cd brightlight && make
    $ mv ./brightlight /usr/local/bin
    $ cd $_ && sudo chown root:root brightlight
    $ sudo u+s brightlight

Then bind keys within i3 configuration file to use it:

    bindsym XF86MonBrightnessUp exec brightlight -i 60
    bindsym XF86MonBrightnessDown exec brightlight -d 60

**Comment by lucagump** [comment]
sudo u+s doesn't work for me (u+s stands for?) .
Backlight works fine also from terminal but can't open "brightness"
Bacetti.

**Comment by anchnk** [comment]
I did installed that on my previous company laptop. To be honest I don't remember everything sharply. I can't find any reference to such flag in the sudo manual. I must have made an typo. I don't know if it has to do with setuid as [brightlight](https://github.com/multiplexd/brightlight) manual is mentionning it:

> this program is intended to be installed setuid root, as the files in sysfs are
owned by user and group root by default

What do you mean by can't open brightness ?

If brightlight works from the terminal then it's just a matter of assigning your keyboard key interrupts to the associated shell command (briglight -i 60 for example). You might need to tweak the value on your laptop too. 

Let me know how it goes

**Comment by nurulmac11** [comment]
> ## Solution
> 
> Using [`brightlight`](https://github.com/multiplexd/brightlight) worked under Ubuntu 16.04
> 
> Clone, install dependencies, compile and install brightlight binary with SUID bit
> 
> ```
> $ git clone https://github.com/multiplexd/brightlight.git
> $ sudo apt install libbsd-dev
> $ cd brightlight && make
> $ mv ./brightlight /usr/local/bin
> $ cd $_ && sudo chown root:root brightlight
> $ sudo u+s brightlight
> ```
> 
> Then bind keys within i3 configuration file to use it:
> 
> ```
> bindsym XF86MonBrightnessUp exec brightlight -i 60
> bindsym XF86MonBrightnessDown exec brightlight -d 60
> ```
worked for me. last line must be;
```
cd /sys/class/backlight/intel_backlight
sudo chmod 777 brightness
```

instead of;
`sudo u+s brightlight
`

**Comment by georgesamy** [comment]
Worked, but instead of :
`$ sudo u+s brightlight`

should be:
`$ sudo chmod u+s brightlight`
